name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches: ["main"] # Or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    # Set a default working directory for most steps in this job
    defaults:
      run:
        working-directory: ./markdown-viewer # <<<<<< KEY CHANGE HERE

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Checkout happens at the repo root, so no working-directory here yet.

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          # Specify the path to package-lock.json relative to the repo root
          cache-dependency-path: ./markdown-viewer/package-lock.json # <<<<<< KEY CHANGE HERE

      - name: Install dependencies
        run: npm ci
        # This will run in ./markdown-viewer due to job defaults

      - name: Build SvelteKit app
        run: npm run build
        # This will run in ./markdown-viewer due to job defaults
        env:
          VITE_STRAPI_URL: ${{ secrets.STRAPI_URL_CLOUD }}
          # NODE_ENV is usually set to 'production' by GitHub Actions for build steps

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The path is relative to the REPO ROOT, so it needs to include the subdirectory
          path: './markdown-viewer/build' # <<<<<< KEY CHANGE HERE (assuming 'build' is output of svelte.config.js)

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4